import type { Wedding } from '@/lib/types'

export interface TemplateMeta {
  id: Wedding['template_id']
  name: string
  description: string
  tags: string[]
  palette: string[]
  ambiance: 'clair' | 'sombre' | 'pastel'
  language?: 'fr' | 'ar'
  preview?: string
  type: 'statique' | 'dynamique'
}

export const TEMPLATES_META: TemplateMeta[] = [
  // ───────── Dynamiques (vidéo / animation) ─────────
  {
    id: 'coeur_dore',
    name: 'Cœur Doré',
    description: 'Romance ivoire & or chaud. Enveloppe à branches dorées qui s\'ouvre comme deux portes sur un sceau cœur. Carte gravée à pivoines blanches sculptées. Compatible mariages internationaux et orientaux.',
    tags: ['Romantique', 'Or', 'Floral', 'International', 'Bismillah'],
    palette: ['#F7ECD5', '#FBF6EA', '#C9A961', '#B8924A'],
    ambiance: 'clair',
    language: 'fr',
    type: 'dynamique',
  },
  {
    id: 'alexa_richard',
    name: 'Alexa & Richard',
    description: 'Romantisme bleu poudré & crème. Ouverture à polygones, vidéo héro, scratch-to-reveal de la date, timeline alternée et section dress code. Élégance anglophone pour mariages internationaux.',
    tags: ['International', 'Romantique', 'Vidéo', 'Interactif'],
    palette: ['#fffdfb', '#64a0bd', '#52839c', '#9bc9e1'],
    ambiance: 'clair',
    language: 'fr',
    type: 'dynamique',
  },
  {
    id: 'viktor_paula',
    name: 'Viktor & Paula',
    description: 'Romance bordeaux & crème. Enveloppe à polygones qui s\'écartent sur une colombe. Hero avec rubis facettés, timeline à colombe animée, séparateurs déchirés. Élégance classique européenne.',
    tags: ['Classique', 'Bordeaux', 'Occidental', 'Gemmes'],
    palette: ['#66021f', '#fffaf8', '#f5ece9', '#4a0116'],
    ambiance: 'sombre',
    language: 'fr',
    type: 'dynamique',
  },

  // ───────── Statiques ─────────
  {
    id: 'bismillah',
    name: 'Bismillah ﷽',
    description: 'Template islamique. Blanc immaculé, calligraphie dorée Thuluth, versets coraniques. Pour mariages religieux traditionnels avec invocation Bismillah.',
    tags: ['Islamique', 'Religieux', 'Traditionnel', 'Coranique'],
    palette: ['#FFFFFF', '#FAF7F0', '#C9A84C', '#1A1A1A'],
    ambiance: 'clair',
    language: 'ar',
    type: 'statique',
  },
  {
    id: 'al_nour',
    name: 'Al-Nour — النور',
    description: 'Invitation classique maghrébine. Parchemin crème, calligraphie Aref Ruqaa, noms en grand, date en texte coulant. Style traditionnel tunisien sobre et élégant.',
    tags: ['Islamique', 'Traditionnel', 'Maghrébin', 'Calligraphie'],
    palette: ['#F5F0E8', '#2C2416', '#8B6914', '#C9A84C'],
    ambiance: 'clair',
    language: 'ar',
    type: 'statique',
  },
  {
    id: 'carte_simple',
    name: 'Carte Simple',
    description: 'Épure absolue. Carte blanche centrée sur fond coloré, bordure or fine, noms en grand script doré. Le minimalisme élégant pour les mariages contemporains.',
    tags: ['Minimaliste', 'Moderne', 'Carte', 'Or'],
    palette: ['#EDE9E2', '#FAFAF8', '#C9A84C', '#2C2416'],
    ambiance: 'clair',
    type: 'statique',
  },
  {
    id: 'toile_bleue',
    name: 'Toile Bleue',
    description: 'Cadre floral bleu marine sur fond beige naturel. Typographie EB Garamond classique, rose bleue entre les noms. Élégance française intemporelle.',
    tags: ['Classique', 'Floral', 'Français', 'Élégant'],
    palette: ['#EAE0D1', '#3D5A8A', '#2C2416', '#8AAAD0'],
    ambiance: 'clair',
    preview: '/assets/template1/exemple1.png',
    type: 'statique',
  },
  {
    id: 'jardin_rose',
    name: 'Jardin Rose',
    description: 'Cadre floral vintage sur fond papier blush. Typographie EB Garamond italique, tons rose poudré et ivoire. Romantisme classique pour mariages printaniers.',
    tags: ['Floral', 'Romantique', 'Vintage', 'Printemps'],
    palette: ['#F0E5E3', '#B87070', '#9A5858', '#3D2B2B'],
    ambiance: 'pastel',
    preview: '/assets/template2/exemple2.png',
    type: 'statique',
  },
  {
    id: 'floral_arch',
    name: 'Floral Arch',
    description: 'Arche florale encadrée de roses corail et feuilles vertes. Script Great Vibes pour les noms, palette vert forêt, corail et gris chaud sur fond crème. Élégant et printanier.',
    tags: ['Floral', 'Arche', 'Script', 'Printanier'],
    palette: ['#f8f7f7', '#497043', '#e38080', '#7b7872'],
    ambiance: 'pastel',
    preview: '/assets/template3/exemple.png',
    type: 'statique',
  },
  {
    id: 'rose_bleu',
    name: 'Rose Bleu',
    description: 'Élégance romantique aux tons bleu ardoise. Bouquet de roses bleues vintage, noms côte à côte en Tangerine calligraphique sur papier crème texturé. Cadre fin en branches délicates.',
    tags: ['Romantique', 'Vintage', 'Bleu', 'Calligraphie'],
    palette: ['#f5ede0', '#6b8fa8', '#8aafc8', '#4a6b82'],
    ambiance: 'clair',
    preview: '/assets/template5/exemple.png',
    type: 'statique',
  },
  {
    id: 'roses_ivoire',
    name: 'Roses Ivoire',
    description: 'Invitation classique American style. Cadre doré aux roses sculptées, fond blanc immaculé, noms en calligraphie Parisienne, date en trois cases typographiques. Élégance intemporelle.',
    tags: ['Classique', 'Doré', 'Calligraphie', 'Américain'],
    palette: ['#FFFFFF', '#82674b', '#9e8060', '#c4a882'],
    ambiance: 'clair',
    preview: '/assets/template4/exemple.png',
    type: 'statique',
  },

  {
    id: 'template_7',
    name: 'Fleurs & Or',
    description: 'Cadre doré multi-lignes à roses bordeaux sur fond beige nacré. Calligraphie Alex Brush pour les prénoms, roses poudre en flancs, petite rose centrale en séparateur. Style Save the Date élégant.',
    tags: ['Floral', 'Doré', 'Classique', 'Save the Date'],
    palette: ['#f8f3ef', '#B8924A', '#7B3A55', '#2C1A10'],
    ambiance: 'clair',
    preview: '/assets/template7/exemple 7.png',
    type: 'statique',
  },
  {
    id: 'template_8',
    name: 'Anneaux Floraux',
    description: 'Fleurs roses en coins sur fond crème doux. Double anneau floral monogramme avec initiales en Great Vibes. Prénoms en grande calligraphie rose. Style romantique contemporain.',
    tags: ['Floral', 'Rose', 'Monogramme', 'Romantique'],
    palette: ['#fffded', '#C06080', '#8B4070', '#3A1A2A'],
    ambiance: 'clair',
    preview: '/assets/template8/exemple8.png',
    type: 'statique',
  },

  // ───────── Statiques arabes ─────────
  {
    id: 'template_7_ar',
    name: 'Fleurs & Or — عربي',
    description: 'Version arabe de Fleurs & Or. Calligraphie Aref Ruqaa, versets coraniques, animation d\'ouverture Bismillah sur fond doré floral bordeaux.',
    tags: ['Islamique', 'Arabe', 'Floral', 'Doré'],
    palette: ['#f8f3ef', '#B8924A', '#7B3A55', '#2C1A10'],
    ambiance: 'clair',
    language: 'ar',
    preview: '/assets/template7/exemple 7.png',
    type: 'statique',
  },
  {
    id: 'template_8_ar',
    name: 'Anneaux Floraux — عربي',
    description: 'Version arabe de Anneaux Floraux. Calligraphie Aref Ruqaa, versets coraniques, animation d\'ouverture Bismillah sur fond floral rose doux.',
    tags: ['Islamique', 'Arabe', 'Floral', 'Romantique'],
    palette: ['#fffded', '#C06080', '#8B4070', '#3A1A2A'],
    ambiance: 'clair',
    language: 'ar',
    preview: '/assets/template8/exemple8.png',
    type: 'statique',
  },
  {
    id: 'toile_bleue_ar',
    name: 'Toile Bleue — عربي',
    description: 'Version arabe de Toile Bleue. Calligraphie Aref Ruqaa, versets coraniques, animation d\'ouverture Bismillah sur fond bleu marine floral.',
    tags: ['Islamique', 'Arabe', 'Floral', 'Calligraphie'],
    palette: ['#EAE0D1', '#3D5A8A', '#C9A84C', '#1A1A1A'],
    ambiance: 'clair',
    language: 'ar',
    preview: '/assets/template1/exemple1.png',
    type: 'statique',
  },
  {
    id: 'jardin_rose_ar',
    name: 'Jardin Rose — عربي',
    description: 'Version arabe de Jardin Rose. Calligraphie Aref Ruqaa, versets coraniques, animation d\'ouverture Bismillah sur fond rose poudré fleuri.',
    tags: ['Islamique', 'Arabe', 'Floral', 'Romantique'],
    palette: ['#F0E5E3', '#B87070', '#C9A84C', '#3D2B2B'],
    ambiance: 'pastel',
    language: 'ar',
    preview: '/assets/template2/exemple2.png',
    type: 'statique',
  },
  {
    id: 'floral_arch_ar',
    name: 'Floral Arch — عربي',
    description: 'Version arabe de Floral Arch. Calligraphie Aref Ruqaa, versets coraniques, animation d\'ouverture Bismillah sur fond arche florale corail et vert.',
    tags: ['Islamique', 'Arabe', 'Floral', 'Arche'],
    palette: ['#f8f7f7', '#497043', '#C9A84C', '#e38080'],
    ambiance: 'pastel',
    language: 'ar',
    preview: '/assets/template3/exemple.png',
    type: 'statique',
  },
  {
    id: 'roses_ivoire_ar',
    name: 'Roses Ivoire — عربي',
    description: 'Version arabe de Roses Ivoire. Calligraphie Aref Ruqaa, versets coraniques, animation d\'ouverture Bismillah sur fond roses sculptées ivoire et or.',
    tags: ['Islamique', 'Arabe', 'Classique', 'Doré'],
    palette: ['#FFFFFF', '#82674b', '#C9A84C', '#c4a882'],
    ambiance: 'clair',
    language: 'ar',
    preview: '/assets/template4/exemple.png',
    type: 'statique',
  },
  {
    id: 'rose_bleu_ar',
    name: 'Rose Bleu — عربي',
    description: 'Version arabe de Rose Bleu. Calligraphie Aref Ruqaa, versets coraniques, animation d\'ouverture Bismillah sur fond roses bleues vintage.',
    tags: ['Islamique', 'Arabe', 'Romantique', 'Bleu'],
    palette: ['#f5ede0', '#6b8fa8', '#C9A84C', '#4a6b82'],
    ambiance: 'clair',
    language: 'ar',
    preview: '/assets/template5/exemple.png',
    type: 'statique',
  },
]